# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Detect Change Points on univariate time series
#'
#' @param S0 First value
#' @param I0 Second value
#' @param MaxTime Prova
#' @param beta_vec Prova
#' @param gamma_0 Prova
#' @param user_seed Prova
#' @return TO DO
#'
SimEpiData <- function(S0, I0, MaxTime, beta_vec, gamma_0, user_seed = 1234L) {
    .Call(`_BayesCPs_SimEpiData`, S0, I0, MaxTime, beta_vec, gamma_0, user_seed)
}

#' Compute the posterior similarity matrix
#'
#' @param M First value
#' @return TO DO
#'
psm <- function(M) {
    .Call(`_BayesCPs_psm`, M)
}

#' Estimate order
#'
#' @param orders_mat First value
#' @return TO DO
#'
#' @export
get_order_VI <- function(orders_mat) {
    .Call(`_BayesCPs_get_order_VI`, orders_mat)
}

#' Detect Change Points on an univariate time series.
#'
#' @param data vector of observations.
#' @param n_iterations number of MCMC iteration.
#' @param q probability of performing a split at each iterations.
#' @param phi parameter \eqn{\phi} of the integrated likelihood function.
#' @param a,b,c parameters of the Normal-Gamma prior for \eqn{\mu} and \eqn{\lambda}.
#' @param par_theta_c,par_theta_d parameters of the shifted Gamma prior for \eqn{\theta}.
#' @param print_progress If TRUE (default) print the progress bar.
#' @param user_seed seed for random distribution generation.
#' @return Function \code{detect_cp_univariate} returns a list containing the following components: \itemize{
#' \item{\code{$orders}} a matrix where each row corresponds to the output order of the corresponding iteration.
#' \item{\code{$sigma_MCMC}} traceplot for \eqn{\sigma}.
#' \item{\code{$sigma_MCMC_01}} a \eqn{0/1} vector, the \eqn{n}-th element is equal to \eqn{1} if the proposed \eqn{\sigma} was accepted, \eqn{0} otherwise.
#' \item{\code{$theta_MCMC}} traceplot for \eqn{\theta}.
#' }
#'
#' @examples
#'
#' data_vec <- as.numeric(c(rnorm(50,0,0.1), rnorm(50,1,0.25)))
#'
#' out <- detect_cp_univariate(data = data_vec,
#'                             n_iterations = 2500,
#'                             q = 0.25,
#'                             phi = 0.1, a = 1, b = 1, c = 0.1)
#'
#' get_order_VI(out$order)
#' @export
detect_cp_univariate <- function(data, n_iterations, q, phi, a, b, c, par_theta_c = 1, par_theta_d = 1, print_progress = TRUE, user_seed = 1234L) {
    .Call(`_BayesCPs_detect_cp_univariate`, data, n_iterations, q, phi, a, b, c, par_theta_c, par_theta_d, print_progress, user_seed)
}

#' Detect Change Points on multivariate time series
#'
#' @param data a matrix where each row is a component of the time series and the columns correpospond to the times.
#' @param n_iterations number of MCMC iterations.
#' @param q probability of permorming a split at each iteration.
#' @param k_0,nu_0,phi_0,m_0 parameters for the Normal-Inverse-Wishart prior for \eqn{(\mu,\lambda)}.
#' @param prior_theta_c,prior_theta_d parameters for the shifted Gamma priod for \eqn{\theta}.
#' @param prior_var_gamma parameters for the Gamma prior for \eqn{\gamma}.
#' @param print_progress If TRUE (default) print the progress bar.
#' @param user_seed seed for random distribution generation.
#' @return Function \code{detect_cp_multiivariate} returns a list containing the following components: \itemize{
#' \item{\code{$orders}} a matrix where each row corresponds to the output order of the corresponding iteration.
#' \item{\code{$gamma_MCMC}} traceplot for \eqn{\gamma}.
#' \item{\code{$gamma_MCMC_01}} a \eqn{0/1} vector, the \eqn{n}-th element is equal to \eqn{1} if the proposed \eqn{\gamma} was accepted, \eqn{0} otherwise.
#' \item{\code{$sigma_MCMC}} traceplot for \eqn{\sigma}.
#' \item{\code{$sigma_MCMC_01}} a \eqn{0/1} vector, the \eqn{n}-th element is equal to \eqn{1} if the proposed \eqn{\sigma} was accepted, \eqn{0} otherwise.
#' \item{\code{$theta_MCMC}} traceplot for \eqn{\theta}.
#' }
#'
#'@examples
#'
#' data_mat <- matrix(NA, nrow = 3, ncol = 100)
#'
#' data_mat[1,] <- as.numeric(c(rnorm(50,0,0.100), rnorm(50,1,0.250)))
#' data_mat[2,] <- as.numeric(c(rnorm(50,0,0.125), rnorm(50,1,0.225)))
#' data_mat[3,] <- as.numeric(c(rnorm(50,0,0.175), rnorm(50,1,0.280)))
#'
#' out <- detect_cp_multivariate(data = data_mat,
#'                               n_iterations = 2500,
#'                               q = 0.25,k_0 = 0.25, nu_0 = 4, phi_0 = diag(1,3,3), m_0 = rep(0,3),
#'                               par_theta_c = 2, par_theta_d = 0.2, prior_var_gamma = 0.1)
#'
#' get_order_VI(out$order)
#' @export
detect_cp_multivariate <- function(data, n_iterations, q, k_0, nu_0, phi_0, m_0, par_theta_c = 1, par_theta_d = 1, prior_var_gamma = 0.1, print_progress = TRUE, user_seed = 1234L) {
    .Call(`_BayesCPs_detect_cp_multivariate`, data, n_iterations, q, k_0, nu_0, phi_0, m_0, par_theta_c, par_theta_d, prior_var_gamma, print_progress, user_seed)
}

#' Clustering Epidemiological survival functions with common changes in time
#'
#' @param data First value
#' @param niter Second value
#' @param M prova
#' @param B prova
#' @param L prova
#' @param gamma prova
#' @param alpha prova
#' @param q prova
#' @param dt prova
#' @param a0 prova
#' @param b0 prova
#' @param c0 prova
#' @param d0 prova
#' @param MH_var prova
#' @param S0 prova
#' @param R0 prova
#' @param p prova
#' @param coarsening prova
#' @param user_seed prova
#' @return TO DO
#'
#' @export
ClusteringCPsEPI <- function(data, niter, M, B, L, gamma = 1/8, alpha = 1, q = 0.1, dt = 0.1, a0 = 4, b0 = 10, c0 = 1, d0 = 1, MH_var = 0.01, S0 = 1, R0 = 0, p = 0.003, coarsening = 1, user_seed = 1234L) {
    .Call(`_BayesCPs_ClusteringCPsEPI`, data, niter, M, B, L, gamma, alpha, q, dt, a0, b0, c0, d0, MH_var, S0, R0, p, coarsening, user_seed)
}

#' Clustering univariate times series with common changes in time
#'
#' @param data a matrix where each row is an observation and each column corresponds to a discrete time.
#' @param n_iterations number of MCMC iterations.
#' @param B number of orders for the normalisation constant.
#' @param L number of split-merge steps for the proposal step.
#' @param gamma,a,b,c parameters \eqn{\gamma} for the integrated likelihood.
#' @param q probability of a split in the split-merge proposal and acceleration step.
#' @param alpha_SM \eqn{\alpha} for the split-merge proposal and acceleration step.
#' @param user_seed seed for random distribution generation.
#' @return TO DO
#'
#' @export
cluster_cp_uni <- function(data, n_iterations, B, L, gamma, a = 1, b = 1, c = 1, q = 0.5, alpha_SM = 0.1, user_seed = 1234L) {
    .Call(`_BayesCPs_cluster_cp_uni`, data, n_iterations, B, L, gamma, a, b, c, q, alpha_SM, user_seed)
}

#' Clustering multivariate times series with common changes in time
#'
#' @param data First value
#' @param n_iterations Second value
#' @param B prova
#' @param L prova
#' @param gamma prova
#' @param k_0 prova
#' @param nu_0 prova
#' @param phi_0 prova
#' @param m_0 prova
#' @param q prova
#' @param alpha_SM prova
#' @param user_seed prova
#' @return TO DO
#'
#' @export
cluster_cp_multi <- function(data, n_iterations, B, L, gamma, k_0, nu_0, phi_0, m_0, q = 0.5, alpha_SM = 0.1, user_seed = 1234L) {
    .Call(`_BayesCPs_cluster_cp_multi`, data, n_iterations, B, L, gamma, k_0, nu_0, phi_0, m_0, q, alpha_SM, user_seed)
}

