# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Clustering multivariate times series with common changes in time
NULL

#' Detect Change Points on univariate time series
#'
#' @param S0 First value
#' @param I0 Second value
#' @param MaxTime
#' @param beta_vec
#' @param gamma_0
#' @param user_seed
#' @return TO DO
#'
SimEpiData <- function(S0, I0, MaxTime, beta_vec, gamma_0, user_seed = 1234L) {
    .Call(`_BayesCPs_SimEpiData`, S0, I0, MaxTime, beta_vec, gamma_0, user_seed)
}

#' Compute the posterior similarity matrix
#'
#' @param M First value
#' @return TO DO
#'
psm <- function(M) {
    .Call(`_BayesCPs_psm`, M)
}

#' Detect Change Points on univariate time series
#'
#' @param data_vec First value
#' @param n_iterations Second value
#' @param q
#' @param phi
#' @param a
#' @param b
#' @param c
#' @param user_seed
#' @param prior_theta_c
#' @param prior_theta_d
#' @return TO DO
#'
DetectCPsUnivariateTS <- function(data_vec, n_iterations, q, phi, a, b, c, user_seed = 1234L, prior_theta_c = 1, prior_theta_d = 1) {
    .Call(`_BayesCPs_DetectCPsUnivariateTS`, data_vec, n_iterations, q, phi, a, b, c, user_seed, prior_theta_c, prior_theta_d)
}

#' Detect Change Points on multivariate time series
#'
#' @param data First value
#' @param n_iterations Second value
#' @param q
#' @param k_0
#' @param nu_0
#' @param phi_0
#' @param m_0
#' @param user_seed
#' @param prior_theta_c
#' @param prior_theta_d
#' @param prior_var_gamma
#' @return TO DO
#'
DetectCPsMultivariateTS <- function(data, n_iterations, q, k_0, nu_0, phi_0, m_0, user_seed = 1234L, prior_theta_c = 1, prior_theta_d = 1, prior_var_gamma = 0.1) {
    .Call(`_BayesCPs_DetectCPsMultivariateTS`, data, n_iterations, q, k_0, nu_0, phi_0, m_0, user_seed, prior_theta_c, prior_theta_d, prior_var_gamma)
}

#' Clustering Epidemiological survival functions with common changes in time
#'
#' @param data First value
#' @param niter Second value
#' @param M
#' @param B
#' @param L
#' @param gamma
#' @param alpha
#' @param q
#' @param dt
#' @param a0
#' @param b0
#' @param c0
#' @param d0
#' @param MH_var
#' @param S0
#' @param R0
#' @param p
#' @param coarsening
#' @user_seed
#' @return TO DO
#'
#'
#'
ClusteringCPsEPI <- function(data, niter, M, B, L, gamma = 1/8, alpha = 1, q = 0.1, dt = 0.1, a0 = 4, b0 = 10, c0 = 1, d0 = 1, MH_var = 0.01, S0 = 1, R0 = 0, p = 0.003, coarsening = 1, user_seed = 1234L) {
    .Call(`_BayesCPs_ClusteringCPsEPI`, data, niter, M, B, L, gamma, alpha, q, dt, a0, b0, c0, d0, MH_var, S0, R0, p, coarsening, user_seed)
}

#' Clustering univariate times series with common changes in time
#'
#' @param data a matrix (nxd) where each row is an observation and each column corresponds to a discrete time
#' @param n_iterations Second value
#' @param B
#' @param L
#' @param gamma
#' @param a
#' @param b
#' @param c
#' @param d
#' @param q
#' @param alpha_SM
#' @param user_seed
#' @return TO DO
#'
#'
#'
ClusteringCPsUnivariateTS <- function(data, n_iterations, B, L, gamma, a = 1, b = 1, c = 1, q = 0.5, alpha_SM = 0.1, user_seed = 1234L) {
    .Call(`_BayesCPs_ClusteringCPsUnivariateTS`, data, n_iterations, B, L, gamma, a, b, c, q, alpha_SM, user_seed)
}

ClusteringCPsMultivariateTS <- function(data, n_iterations, B, L, gamma, k_0, nu_0, phi_0, m_0, q = 0.5, alpha_SM = 0.1, user_seed = 1234L) {
    .Call(`_BayesCPs_ClusteringCPsMultivariateTS`, data, n_iterations, B, L, gamma, k_0, nu_0, phi_0, m_0, q, alpha_SM, user_seed)
}

